### ISSUE TITLE
"pngu.h" not found

### ISSUE THREAD

**Issue by WiseMatthack** [DaeFennek/libpega#1]
when trying to compile the game using the `make` command, it returns me this error:

`fatal error: pngu.h: No such file or directory
 #include <pngu.h>
          ^~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:13: wii_camera.o] Error 1
make: *** [Makefile:114: build] Error 2`

it seems like pngu.h isn't included in the source code

**Comment by Heath123** [comment]
Why did you close this with no explanation? I'm getting this too

**Comment by WiseMatthack** [comment]
simply because you need to install grrlib first :p
