### ISSUE TITLE
black screen on start

### ISSUE THREAD

**Issue by kdude729** [DaeFennek/libpega#10]
hi um when i load wiicraft my screen turns black and i cant do anything except shutdown every thing

**Comment by kdude729** [comment]
please help

**Comment by ColorVoid** [comment]
hello, i have a problem id also like to solve, maybe we can work together?

**Comment by kdude729** [comment]
sorry i haven't looked at this in a while but i think i found the problem

**Comment by kdude729** [comment]
so im pretty sure that the reason is because are wiis are offline what i mean by that is there not connected to nintendo wfc

**Comment by blokos0** [comment]
> so im pretty sure that the reason is because are wiis are offline what i mean by that is there not connected to nintendo wfc

isnt nintendo wfc dead?

**Comment by kdude729** [comment]
yes but there is a way now to boot it back up

**Comment by kdude729** [comment]
but i tried that and it didnt work

**Comment by kdude729** [comment]
but also my wii just has a lot of problems like loading systems wiiload dosent work

**Comment by kdude729** [comment]
it might just be because of the fact that my wii is not like other wiis

**Comment by kdude729** [comment]
the one other option it could be is the run make thing doesn't work it just says nothing to be done for the folder wiicraft
make: Nothing to be done for 'C:\Users\kevin\Downloads\Wiicraft_Alpha_1_0'.

**Comment by kperdlich** [comment]
Did you follow the `README`?
Your wii must be connect to a network that can access your minecraft server. Running the `.dol` directly from sd card can cause problems that I haven't investigated. Better use `wiiload`.

Rebuilding via make will not fix your connection problems to the server. Make sure you adjusted the `Game.ini` on the sd card according to your server config: 

```
[MinecraftServer]
Host = 192.168.0.144
Port = 25565
```

**Comment by kdude729** [comment]
my wiiload does not work I tried installing it multiple times and every time i double-click it it says it opened but the wii does not recieve anything

**Comment by kdude729** [comment]
and i did adjust the game.ini preferences

**Comment by kdude729** [comment]
could you tell me how to setup wiilod

**Comment by kdude729** [comment]
i got it to work you have to use wiiload but now it says this
![05312022_011230A](https://user-images.githubusercontent.com/85129985/171267440-04fb18f4-6c26-4af3-958b-ab37e17e8621.jpg)

**Comment by kdude729** [comment]
btw @ColorVoid you have to download hackmii installer and inside the hackmii folder you will find wiiload that is how you get the files to wiiload

**Comment by kdude729** [comment]
im realizing looking at this text that i got my server ip wrong

**Comment by kdude729** [comment]
now it keeps kicking me out of the server!

**Comment by kdude729** [comment]
failed to authenticate username

**Comment by kdude729** [comment]
Disconnecting WiicraftPlayer : Failed to verify username!

**Comment by kdude729** [comment]
this is what the server gives me

**Comment by kdude729** [comment]
nevermind figured that out as well i needed to turn on offline mode

**Comment by kdude729** [comment]
now it gives me this error

**Comment by kdude729** [comment]
Couldn't find/create instance of packetID 18
