### ISSUE TITLE
Support for newer Minecraft versions

### ISSUE THREAD

**Issue by Heath123** [DaeFennek/libpega#2]
1.2.5 is very old now. If it was at least updated to a version compatible with ProtocolSupport then it would be a lot more useful.

**Comment by kperdlich** [comment]
Why would it be more useful?

**Comment by Heath123** [comment]
So we can join modern servers and we don’t have to make everyone downgrade to a really old version to play with Wii users

**Comment by Heath123** [comment]
Even if it only supported 1.4.7 it could join 1.15.2 servers through ProtocolSupport

**Comment by kperdlich** [comment]
Too much effort for the moment. Maybe someone else can do that.

**Comment by Heath123** [comment]
I don't think it makes sense to close the issue until it's done, and I don't think it would be that much effort to update the protocol compared to making a full voxel engine with networking on a console from 2006, but OK...
