### ISSUE TITLE
Couldn't find/create instance of packetID 18

### ISSUE THREAD

**Issue by CorkGogo2010** [DaeFennek/libpega#3]
When I try to connect to my server it crashes almost instantly with this error. Also, there is no server.properties attached in the release as you said in the instructions. Attached is my server.properties, the error on the Wii, and the log from the server. Note that I hid my IP address and that default username from the source code came back, even though I changed it in Game.ini. I also launched the .dol directly from the Wii, as I could not get wiiload to work for me.
[Server log.txt](https://github.com/kperdlich/wiicraft/files/4210047/Server.log.txt)
[server.properties.txt](https://github.com/kperdlich/wiicraft/files/4210048/server.properties.txt)
[Wii crash log.txt](https://github.com/kperdlich/wiicraft/files/4210050/Wii.crash.log.txt)

**Comment by iyenal** [comment]
I got the same issue unfortunately, hope it'll get fixed soon. Besides I congratulate your effort for making a such great port of Minecraft for the Wii.

**Comment by kperdlich** [comment]
sorry, I updated the release.
Btw in order to get wiiload running you have to add a system variable called "WIILOAD" with a value like "tcp:192.168.0.115"

**Comment by kperdlich** [comment]
> When I try to connect to my server it crashes almost instantly with this error. Also, there is no server.properties attached in the release as you said in the instructions. Attached is my server.properties, the error on the Wii, and the log from the server. Note that I hid my IP address and that default username from the source code came back, even though I changed it in Game.ini. I also launched the .dol directly from the Wii, as I could not get wiiload to work for me.
> [Server log.txt](https://github.com/kperdlich/wiicraft/files/4210047/Server.log.txt)
> [server.properties.txt](https://github.com/kperdlich/wiicraft/files/4210048/server.properties.txt)
> [Wii crash log.txt](https://github.com/kperdlich/wiicraft/files/4210050/Wii.crash.log.txt)
