### ISSUE TITLE
Add support for minetest?

### ISSUE THREAD

**Issue by wuniversales** [DaeFennek/libpega#7]
I don't know if it will be possible, I suppose yes, it would be great to be able to use minetest together with mineclone 2.
Minetest: https://www.minetest.net/
Mineclone 2 MOD:https://git.minetest.land/Wuzzy/MineClone2
Cheers

**Comment by kperdlich** [comment]
What does that have to do with Wiicraft?

**Comment by wuniversales** [comment]
Very much, it is still a "minecraft", but open source, I think it will give you less problems than the official minecraft servers.

**Comment by halotroop2288** [comment]
Minetest is not Minecraft at all. It is a completely different voxel game with a completely different set of base content and a completely different implementation.
You would be better off using something like Classicube if you wanted to add support for other voxel engines or games.

**Comment by kperdlich** [comment]
Doesn't make sense!
